# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_auto_20180627_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='base',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='track',
            name='use',
            field=models.TextField(max_length=256),
        ),
    ]
