# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_auto_20180627_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_id', models.IntegerField(default=1)),
                ('name', models.TextField(max_length=256)),
                ('student_id', models.TextField(max_length=256)),
                ('track', models.TextField(max_length=256)),
                ('base', models.TextField(max_length=256)),
                ('use', models.TextField(max_length=256)),
            ],
        ),
    ]
