# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(default=1)),
                ('name', models.TextField(max_length=30)),
                ('base', models.TextField(max_length=30)),
                ('use', models.TextField(max_length=30)),
            ],
        ),
    ]
